BPMeasurement/Models/BPContext.cs
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Reflection.Emit;
using System.Security.AccessControl;

namespace BPMeasurement.Models
{
    public class BPContext : DbContext
    {
        public BPContext(DbContextOptions<BPContext> options) : base(options)
        {
        }

        public DbSet<BloodMeasurement> BPMeasurements { get; set; }
        public DbSet<Position> Positions { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            
            
            modelBuilder.Entity<Position>().HasData(
                new Position { PositionId = "A", Name = "Standing" },
                new Position { PositionId = "T", Name = "Sitting" },
                new Position { PositionId = "L", Name = "Lying Down" }
            );
            DateTime customDate = new DateTime(2023, 09, 12);
            modelBuilder.Entity<BloodMeasurement>().HasData(
               new BloodMeasurement
               {
                   BPId = 1,
                   Systolic = 118,
                   Diastolic = 70,
                   PositionId = "A",
                   Date = customDate,
                 
               },
               new BloodMeasurement
               {
                   BPId = 2,
                   Systolic = 127,
                   Diastolic = 78,
                   PositionId="L",
                   Date = customDate,
                   
               },
               new BloodMeasurement
               {
                   BPId = 3,
                   Systolic = 137,
                   Diastolic = 85,
                   PositionId = "T",
                   Date = customDate,
                   
               },
               new BloodMeasurement
               {
                   BPId = 4,
                   Systolic = 150,
                   Diastolic = 90,
                   PositionId = "T",
                   Date = customDate,

               },
               new BloodMeasurement
               {
                   BPId = 5,
                   Systolic = 190,
                   Diastolic = 130,
                   PositionId = "T",
                   Date = customDate,

               }
           );
    }   }
}

BPMeasurement/Models/BloodMeasurement.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;

namespace BPMeasurement.Models
{
    public class BloodMeasurement
    {
        [Key]
        public int BPId { get; set; }

        [Required]
        [Range(20, 400, ErrorMessage = "Systolic Values must be positive and between 20 and 400")]
        public int Systolic { get; set; }

        [Required]
        [Range(10, 300, ErrorMessage = "Diastolic Values must be positive and between 10 and 300")]
        public int Diastolic { get; set; }

        [Required(ErrorMessage = "Please specify a date and time")]
        public DateTime? Date {  get; set; }


        [Required(ErrorMessage = "Please specify a position for the measurement")]
        public string PositionId { get; set; }

        [ValidateNever]
        public Position Position { get; set; }

        public string Category
        {
            get
            {
                int systolic = Systolic;
                int diastolic = Diastolic;

                if (systolic < 120 && diastolic < 80)
                {
                    return "Normal";
                }
                else if (systolic >= 120 && systolic <= 129 && diastolic < 80)
                {
                    return "Elevated";
                }
                else if ((systolic >= 130 && systolic <= 139) || (diastolic >= 80 && diastolic <= 89))
                {
                    return "Hypertension Stage 1";
                }
                else if ((systolic >= 140) || (diastolic >= 90))
                {
                    return "Hypertension Stage 2";
                }
                else
                {
                    return "Hypertensive Crisis";
                }
            }
        }
    }
}

BPMeasurement/Models/ErrorViewModel.cs
namespace BPMeasurement.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BPMeasurement/Models/Position.cs
namespace BPMeasurement.Models
{
    public class Position
    {
        public string PositionId { get; set; }
        public string Name { get; set; }
    }
}

BPMeasurement/Controllers/BPController.cs
using BPMeasurement.Models;
using Microsoft.AspNetCore.Mvc;

namespace BPMeasurement.Controllers
{   
    public class BPController : Controller
    {
        private BPContext context { get; set; }

        public BPController(BPContext ctx)
        {
            context = ctx;
        }


        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            ViewBag.Positions
               = context.Positions.OrderBy(g => g.Name).ToList();
            return View("Edit", new BloodMeasurement());
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            ViewBag.Action = "Edit";
            ViewBag.Positions
               = context.Positions.OrderBy(g => g.Name).ToList();
            var measurement = context.BPMeasurements.Find(id);
            return View(measurement);
        }

        [HttpPost]
        public IActionResult Edit(BloodMeasurement measurement)
        {
            if (ModelState.IsValid)
            {
                if (measurement.BPId == 0)
                    context.BPMeasurements.Add(measurement);
                else
                    context.BPMeasurements.Update(measurement);
                context.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Action =
                    (measurement.BPId == 0) ? "Add" : "Edit";
                ViewBag.Positions
               = context.Positions.OrderBy(g => g.Name).ToList();
                return View(measurement);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var measurement = context.BPMeasurements.Find(id);
            return View(measurement);
        }

        [HttpPost]
        public IActionResult Delete(BloodMeasurement measurement)
        {
            context.BPMeasurements.Remove(measurement);
            context.SaveChanges();
            return RedirectToAction("Index", "Home");
        }
    }
}

BPMeasurement/Controllers/HomeController.cs
using BPMeasurement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace BPMeasurement.Controllers
{
    public class HomeController : Controller
    {
      
        private BPContext context { get; set; }

        public HomeController(BPContext ctx) =>
            context = ctx;

        public IActionResult Index()
        {
           
            var measurements = context.BPMeasurements.Include(m => m.Position)
                .OrderBy(m => m.BPId).ToList();
            return View(measurements);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BPMeasurement/Views/BP/Delete.cshtml
@model BloodMeasurement
@{
    ViewBag.Title = "Delete";
}
<h2>Confirm Deletion</h2>
<h3>@Model.Systolic/@Model.Diastolic (@Model.Date) </h3>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="BPId" />

    <button type="submit" class="btn btn-primary">
        Delete
    </button>
    <a asp-controller="Home" asp-action="Index"
       class="btn btn-primary">Cancel</a>
</form>

BPMeasurement/Views/BP/Edit.cshtml
@model BloodMeasurement
@{
    string title = ViewBag.Action + " BP";
    ViewBag.Title = title;
}
<h2>@ViewBag.Title</h2>

<form asp-action="Edit" method="post">
    <div asp-validation-summary="All"
         class="text-danger">
    </div>

    <div class="form-group">
        <label asp-for="Systolic">Systolic</label>
        <input asp-for="Systolic" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Diastolic">Diastolic</label>
        <input asp-for="Diastolic" class="form-control">
    </div>
    

    <div class="form-group">
        <label asp-for="PositionId">Position</label>
        <select asp-for="PositionId" class="form-control">
            <option value="">select a genre</option>
            @foreach (Position g in ViewBag.Positions)
            {
                <option value="@g.PositionId">
                    @g.Name
                </option>
            }
        </select>
    </div>
    <div class="form-group">
        <label asp-for="Date">Date of measurement</label>
        <input asp-for="Date" class="form-control">
    </div>
    <input type="hidden" asp-for="BPId" />

    <button type="submit" class="btn btn-primary">
        @ViewBag.Action
    </button>
    <a asp-controller="Home" asp-action="Index"
       class="btn btn-primary">Cancel</a>
</form>

BPMeasurement/Views/Home/Index.cshtml
@model List<BloodMeasurement>
@{
    ViewData["Title"] = "All Measurment";
}

<div class="mb-2">
    <a asp-controller="BP" asp-action="Add">Add New BP Measurment</a> | <a asp-controller="BP" asp-action="BPCategory">Information on BP Measurements</a>
</div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Readings</th>
            <th>Category</th>
            <th>Position</th> 
            <th>Date Taken</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var measurement in Model)
        {
            <tr>
                <td style ="color: @GetCategoryColor(measurement.Category)">@measurement.Systolic/@measurement.Diastolic</td>
                 <td style="color: @GetCategoryColor(measurement.Category)">@measurement.Category</td>

                <td>@measurement.Position.Name</td>

                <td> @measurement.Date</td>

                @* <div class="form-group">
                    <label for="date">Measurement Date</label>
                    <input type="text" id="date" class="datepicker form-control" />
                </div> *@

                <td>
                    <a asp-controller="BP" asp-action="Edit"
                       asp-route-id="@measurement.BPId">Edit</a>
                    <a asp-controller="BP" asp-action="Delete"
                       asp-route-id="@measurement.BPId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@functions {
    string GetCategoryColor(string category)
    {
        switch (category)
        {
            case "Normal":
                return "darkgreen";
            case "Elevated":
                return "blue";
            case "Hypertension Stage 1":
                return "orange";
            case "Hypertension Stage 2":
                return "orangered";
            case "Hypertensive Crisis":
                return "darkred";
            default:
                return "black"; // Default color if category is not recognized
        }
    }
}

BPMeasurement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BPMeasurement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BPMeasurement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BPMeasurement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BPMeasurement - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        $(document).ready(function () {
            $(".datepicker").datepicker({
                dateFormat: 'yy-mm-dd', // Change the date format
                showOtherMonths: true, // Show dates from other months
                selectOtherMonths: true // Allow selecting dates from other months
            });
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>